### ISSUE TITLE
Add possibility to search macro names in lowercase and with extension

### ISSUE THREAD

**Issue by JeffyOLOLO** [eclipse/che-che4z-lsp-for-hlasm#4]
Hello!

In our project we store macros in lowercase and with extension _.sm_.
E.g. strucs/if.sm; maclib/@wto.sm

Is it possible to search for macros in this case? If not, will it be difficult to add?

Thank you!

**Comment by michalbali256** [comment]
Hi!

Thank you for your feedback!

At the moment, it is only possible to use macros that are in a file that is named exactly same as the macro.

It should not be too hard to add to a future release.

**Comment by marcel1hruska** [comment]
Hi!

Today we released version 0.10.0, which supports your use case.

We added an `alwaysRecognize` array of wildcards to the `pgm_conf.json`. If you define a wildcard that represents a custom extension (e.g. `"*.sm"`), you may use macro and copy files with this extension. Furthermore, we do not require these files to be upper-case.

**Comment by JeffyOLOLO** [comment]
Hello, I updated the plugin and configured as you adviced but it doesn't work :(
For example, we use maclib/if.sm, maclib/endif.sm, maclib/@wto.sm, in source code it looks like:
```
       IF (FLAG1)
            @WTO   'SOMETHING'
       ENDIF
```
My proc_grps.json:
```
{
  "pgroups": [
    {
      "name": "macros",
      "libs": [
        "C:/Users/ ... /macapi",
        "C:/Users/ ... /maclib"
      ]
    }
  ]
}
```
pgm_conf.json:
```
{
  "pgms": [
    {
      "program": "C:/Users/ ... /asm/*",
      "pgroup": "macros"
    }
  ],
  "alwaysRecognize" : [
    "C:/Users/ ... /macapi/*.sm",
    "C:/Users/ ... /maclib/*.sm"
  ]
}
```
There are absolute path but it doesn't work with relative path too.

**Comment by michalbali256** [comment]
I am sorry but I cannot recreate your problem.

The paths should be relative to your workspace.
Are you sure that you are using the 0.10.0 release? Also, what operating system do you use?

[example_ws.zip](https://github.com/eclipse/che-che4z-lsp-for-hlasm/files/4450371/example_ws.zip): here is an example workspace that works on my machine.

If you will still experience the problem can you wrap your workspace in a zip and attach it?

**Comment by JeffyOLOLO** [comment]
I have Windows 10.0.17134
Unfortunatly it is working now on workspace level...
But absolute path still not working. Can you try to replace paths in your example by absolute?

**Comment by JeffyOLOLO** [comment]
So... absolute paths also works for me.
On which event the plugin re-read json config files?

**Comment by marcel1hruska** [comment]
Every time you restart the extension or save the config file, the plugin retrieves new information from it. However, you should also re-parse the file by re-opening it or by making some change to it, so that it can properly find the "new" macro.

**Comment by JeffyOLOLO** [comment]
I found out that when I specify an absolute path in pgroups, I must also add the path to alwaysRecognize pattern so that the plugin correctly finds macros with extension.

For example, pgroup contains : `"C:/Users/ ... /maclib"`
If I specify "global" pattern in alwaysRecognize `"*.sm"` it doesn't work for files outside a workspace. 
For everything to work, I must specify patterns as `"*.sm", "C:/Users/ ... /maclib/*.sm"`

Does it work as expected?

**Comment by marcel1hruska** [comment]
As for now, we did not focus on absolute paths, as we thought the user would have all of his include files inside the workspace and therefore would use the relative paths.

Could you please explain us why do you need absolute paths? We may look into them in close future.

**Comment by JeffyOLOLO** [comment]
I have 3 projects, they all have the same structure including `maclib/*.sm`. One of them is common library which is used in 2 other projects. 
It's better to specify absolute path to a library maclib than copy the maclib to the both projects.

**Comment by marcel1hruska** [comment]
Good to know! We will try to address this issue in the near future.
